
version: "2.0"

services:
  web:
    image: cryptoandcoffee/walletnode:btc
    expose:
      - port: 22
        as: 22
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 512Mi
        storage:
          size: 512Mi
  placement:
    westcoast:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1f0kvpxaw85wargz4xzfx8uqukqrgcgkd5krd99"
      pricing:
        web: 
          denom: uakt
          amount: 1000

deployment:
  web:
    westcoast:
      profile: web
      count: 1
